train:
  # Run on debug mode (which enables more logging)
  debug: False
  # Training batch size for images. FasterRCNN currently only supports 1
  batch_size: 1
  # Where to save the models
  model_dir: models/
  # Checkpoint file from where to load existing var values
  checkpoint_file:
  # Ignore scope when loading from checkpoint (useful when training RPN first
  # and then RPN + RCNN)
  ignore_scope:
  # Where to save the logs for TensorBoard
  log_dir: /tmp/luminoth/
  # Save a checkpoint after that many batches
  save_every: 1000
  # Enables TensorFlow debug mode, which stops and lets you analyze Tensors
  # after each Session.run
  tf_debug: False
  # Run name is used for better checkpoint and log hierarchy
  run_name:
  # Disables logging and saving checkpoints
  no_log: False
  # Displays debugging images with results every N batches. Debug mode must be
  # enabled
  display_every: 1
  # Shuffle the dataset. It should only be disabled when trying to reproduce
  # some problem on some sample
  random_shuffle: True
  # Save Tensorboard timeline
  save_timeline: False
  summary_every: 1
  full_trace: False
  initial_learning_rate: 0.0001
  learning_rate_decay: 400000
  learning_rate_decay_method: piecewise_constant
  optimizer_type: momentum
  momentum: 0.9
  num_epochs: 10000

  # TODO: Remove this arg passed by Google Cloud ML.
  job_dir: null

dataset:
  dir: 'datasets/voc/tf'
  split: train
  image_preprocessing:
    min_size: 600
    max_size: 1024
  data_augmentation:
    flip_y: True

network:
  num_classes: 20
  with_rcnn: True

pretrained:
  net: vgg_16
  trainable: True
  weights:
  endpoint: vgg_16/conv5/conv5_1
  finetune_num_layers: 3
  weight_decay: 0.0005

loss:
  rpn_cls_loss_weight: 1.0
  rpn_reg_loss_weights: 2.0
  rcnn_cls_loss_weight: 1.0
  rcnn_reg_loss_weights: 2.0

anchors:
  base_size: 256
  scales: [0.5, 1, 2]
  ratios: [0.5, 1, 2]
  stride: 16

rpn:
  num_channels: 512
  kernel_shape: [3, 3]
  initializer:
    type: truncated_normal_initializer
    mean: 0.0
    stddev: 0.01
  l2_regulalization_scale: 0.0005  # disable using 0
  activation_function: relu6

  proposals:
    pre_nms_top_n: 12000
    post_nms_top_n: 2000
    nms_threshold: 0.6
    min_size: 0  # disable using 0

  target:
    allowed_border: 0
    clobber_positives: False
    foreground_threshold: 0.7
    background_threshold_high: 0.3
    background_threshold_low: 0.
    foreground_fraction: 0.5
    minibatch_size: 256
    random_seed:  # only to be used for debugging

rcnn:
  enabled: True  # if disabled, then the rest of the config values will not be used.
  layer_sizes: [4096, 4096]
  dropout_keep_prop: 1.0
  activation_function: relu6
  initializer:
    type: variance_scaling_initializer
    factor: 1.0
    uniform: True
    mode: FAN_AVG
  l2_regulalization_scale: 0.0005

  roi:
    pooling_mode: crop
    pooled_width: 7
    pooled_height: 7
    padding: VALID

  proposals:
    class_max_detections: 100
    class_nms_threshold: 0.6
    total_max_detections: 300

  target:
    foreground_fraction: 0.25
    minibatch_size: 64
    foreground_threshold: 0.5
    background_threshold_high: 0.5
    background_threshold_low: 0.1
